### ISSUE TITLE
github.com/gofrs/uuid removing support for Version 2 UUID generation

### ISSUE THREAD

**Issue by theckman** [phogolabs/schema#1]
Hi there,

I wanted to reach out and make you aware of this PR that will likely be merged in to the `github.com/gofrs/uuid` repo that will result in a new major version being cut: https://github.com/gofrs/uuid/pull/71

I found that you appear to consume the code that's going to be removed here, and thought you may want to preemptively remove it:

https://github.com/phogolabs/schema/blob/ce34519ba966a2f8e41672f19ae49f423d3751e1/uuid.go#L19

Cheers!
-Tim

**Comment by iamralch** [comment]
Sorry I haven't seen the comment. Thank you for letting me know. I will do change it after the major refactoring that I am planning to do
